///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TesteTortoise
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("cecfa0e6-02c5-43d8-8e47-86480071b654", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TesteTortoiseRepository repository.
        /// </summary>
        public static TesteTortoiseRepository repo = TesteTortoiseRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.0;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Windows\\System32\\notepad.exe' with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\Windows\\System32\\notepad.exe", "", "C:\\Windows\\System32", false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{RShiftKey down}T{RShiftKey up}este{Space down}1{Space up}23'.", new RecordItemIndex(1));
            Keyboard.Press("{RShiftKey down}T{RShiftKey up}este{Space down}1{Space up}23");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UntitledNotepad.File' at 5;6.", repo.UntitledNotepad.FileInfo, new RecordItemIndex(2));
            repo.UntitledNotepad.File.Click("5;6");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UntitledNotepad.Text15' at 430;118.", repo.UntitledNotepad.Text15Info, new RecordItemIndex(3));
            repo.UntitledNotepad.Text15.Click("430;118");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'UntitledNotepad.Text15' at 272;63.", repo.UntitledNotepad.Text15Info, new RecordItemIndex(4));
            repo.UntitledNotepad.Text15.MoveTo("272;63");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'Explorer.List1' at 429;247.", repo.Explorer.List1Info, new RecordItemIndex(5));
            repo.Explorer.List1.MoveTo("429;247");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey}' with focus on 'UntitledNotepad.Text15'.", repo.UntitledNotepad.Text15Info, new RecordItemIndex(6));
            repo.UntitledNotepad.Text15.PressKeys("{LControlKey}");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UntitledNotepad.Edit' at 17;12.", repo.UntitledNotepad.EditInfo, new RecordItemIndex(7));
            repo.UntitledNotepad.Edit.Click("17;12");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Notepad.Font' at 38;8.", repo.Notepad.FontInfo, new RecordItemIndex(8));
            repo.Notepad.Font.Click("38;8");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Font.Text1001' at 28;5.", repo.Font.Text1001Info, new RecordItemIndex(9));
            repo.Font.Text1001.Click("28;5");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '15' with focus on 'Font.Text1001'.", repo.Font.Text1001Info, new RecordItemIndex(10));
            repo.Font.Text1001.PressKeys("15");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Font.ButtonOK' at 70;6.", repo.Font.ButtonOKInfo, new RecordItemIndex(11));
            repo.Font.ButtonOK.Click("70;6");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UntitledNotepad.File' at 19;11.", repo.UntitledNotepad.FileInfo, new RecordItemIndex(12));
            repo.UntitledNotepad.File.Click("19;11");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Notepad.Exit' at 48;9.", repo.Notepad.ExitInfo, new RecordItemIndex(13));
            repo.Notepad.Exit.Click("48;9");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Notepad1.DontSave' at 34;9.", repo.Notepad1.DontSaveInfo, new RecordItemIndex(14));
            repo.Notepad1.DontSave.Click("34;9");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
