///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TesteTortoise
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TesteTortoiseRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.1")]
    [RepositoryFolder("3c2c961a-3564-4d41-91b3-1756b94141d2")]
    public partial class TesteTortoiseRepository : RepoGenBaseFolder
    {
        static TesteTortoiseRepository instance = new TesteTortoiseRepository();
        TesteTortoiseRepositoryFolders.UntitledNotepadAppFolder _untitlednotepad;
        TesteTortoiseRepositoryFolders.ExplorerAppFolder _explorer;
        TesteTortoiseRepositoryFolders.NotepadAppFolder _notepad;
        TesteTortoiseRepositoryFolders.FontAppFolder _font;
        TesteTortoiseRepositoryFolders.Notepad1AppFolder _notepad1;

        /// <summary>
        /// Gets the singleton class instance representing the TesteTortoiseRepository element repository.
        /// </summary>
        [RepositoryFolder("3c2c961a-3564-4d41-91b3-1756b94141d2")]
        public static TesteTortoiseRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TesteTortoiseRepository() 
            : base("TesteTortoiseRepository", "/", null, 0, false, "3c2c961a-3564-4d41-91b3-1756b94141d2", ".\\RepositoryImages\\TesteTortoiseRepository3c2c961a.rximgres")
        {
            _untitlednotepad = new TesteTortoiseRepositoryFolders.UntitledNotepadAppFolder(this);
            _explorer = new TesteTortoiseRepositoryFolders.ExplorerAppFolder(this);
            _notepad = new TesteTortoiseRepositoryFolders.NotepadAppFolder(this);
            _font = new TesteTortoiseRepositoryFolders.FontAppFolder(this);
            _notepad1 = new TesteTortoiseRepositoryFolders.Notepad1AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("3c2c961a-3564-4d41-91b3-1756b94141d2")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The UntitledNotepad folder.
        /// </summary>
        [RepositoryFolder("4ddf9ff5-fd72-426f-82b2-860d9ceacb1b")]
        public virtual TesteTortoiseRepositoryFolders.UntitledNotepadAppFolder UntitledNotepad
        {
            get { return _untitlednotepad; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("dd7f4329-3313-4375-bf04-28aba9acf7e5")]
        public virtual TesteTortoiseRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The Notepad folder.
        /// </summary>
        [RepositoryFolder("ec617235-78fc-46a8-966a-87d1d614a79c")]
        public virtual TesteTortoiseRepositoryFolders.NotepadAppFolder Notepad
        {
            get { return _notepad; }
        }

        /// <summary>
        /// The Font folder.
        /// </summary>
        [RepositoryFolder("73535243-5646-4236-b57f-f63f86fb8dcc")]
        public virtual TesteTortoiseRepositoryFolders.FontAppFolder Font
        {
            get { return _font; }
        }

        /// <summary>
        /// The Notepad1 folder.
        /// </summary>
        [RepositoryFolder("5b5e43a8-e935-4170-a618-d0fece9aafdf")]
        public virtual TesteTortoiseRepositoryFolders.Notepad1AppFolder Notepad1
        {
            get { return _notepad1; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.1")]
    public partial class TesteTortoiseRepositoryFolders
    {
        /// <summary>
        /// The UntitledNotepadAppFolder folder.
        /// </summary>
        [RepositoryFolder("4ddf9ff5-fd72-426f-82b2-860d9ceacb1b")]
        public partial class UntitledNotepadAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _fileInfo;
            RepoItemInfo _text15Info;
            RepoItemInfo _editInfo;

            /// <summary>
            /// Creates a new UntitledNotepad  folder.
            /// </summary>
            public UntitledNotepadAppFolder(RepoGenBaseFolder parentFolder) :
                    base("UntitledNotepad", "/form[@title='Untitled - Notepad']", parentFolder, 30000, null, true, "4ddf9ff5-fd72-426f-82b2-860d9ceacb1b", "")
            {
                _fileInfo = new RepoItemInfo(this, "File", "?/?/menuitem[@accessiblename='File']", 30000, null, "bb9eafe3-80c5-4c0a-86d0-2ebaf508796e");
                _text15Info = new RepoItemInfo(this, "Text15", "text[@controlid='15']", 30000, null, "f136504b-cc5d-4e15-81e2-351dee255727");
                _editInfo = new RepoItemInfo(this, "Edit", "?/?/menuitem[@accessiblename='Edit']", 30000, null, "289cffd3-f813-42dd-aaa7-682441b407cb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4ddf9ff5-fd72-426f-82b2-860d9ceacb1b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4ddf9ff5-fd72-426f-82b2-860d9ceacb1b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The File item.
            /// </summary>
            [RepositoryItem("bb9eafe3-80c5-4c0a-86d0-2ebaf508796e")]
            public virtual Ranorex.MenuItem File
            {
                get
                {
                    return _fileInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The File item info.
            /// </summary>
            [RepositoryItemInfo("bb9eafe3-80c5-4c0a-86d0-2ebaf508796e")]
            public virtual RepoItemInfo FileInfo
            {
                get
                {
                    return _fileInfo;
                }
            }

            /// <summary>
            /// The Text15 item.
            /// </summary>
            [RepositoryItem("f136504b-cc5d-4e15-81e2-351dee255727")]
            public virtual Ranorex.Text Text15
            {
                get
                {
                    return _text15Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text15 item info.
            /// </summary>
            [RepositoryItemInfo("f136504b-cc5d-4e15-81e2-351dee255727")]
            public virtual RepoItemInfo Text15Info
            {
                get
                {
                    return _text15Info;
                }
            }

            /// <summary>
            /// The Edit item.
            /// </summary>
            [RepositoryItem("289cffd3-f813-42dd-aaa7-682441b407cb")]
            public virtual Ranorex.MenuItem Edit
            {
                get
                {
                    return _editInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Edit item info.
            /// </summary>
            [RepositoryItemInfo("289cffd3-f813-42dd-aaa7-682441b407cb")]
            public virtual RepoItemInfo EditInfo
            {
                get
                {
                    return _editInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("dd7f4329-3313-4375-bf04-28aba9acf7e5")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _list1Info;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/desktop[@processname='explorer']", parentFolder, 30000, null, true, "dd7f4329-3313-4375-bf04-28aba9acf7e5", "")
            {
                _list1Info = new RepoItemInfo(this, "List1", "?/?/list[@controlid='1']", 30000, null, "aa6826b7-07f0-493d-b15f-c1e594b6845b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("dd7f4329-3313-4375-bf04-28aba9acf7e5")]
            public virtual Ranorex.Desktop Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Desktop>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("dd7f4329-3313-4375-bf04-28aba9acf7e5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The List1 item.
            /// </summary>
            [RepositoryItem("aa6826b7-07f0-493d-b15f-c1e594b6845b")]
            public virtual Ranorex.List List1
            {
                get
                {
                    return _list1Info.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The List1 item info.
            /// </summary>
            [RepositoryItemInfo("aa6826b7-07f0-493d-b15f-c1e594b6845b")]
            public virtual RepoItemInfo List1Info
            {
                get
                {
                    return _list1Info;
                }
            }
        }

        /// <summary>
        /// The NotepadAppFolder folder.
        /// </summary>
        [RepositoryFolder("ec617235-78fc-46a8-966a-87d1d614a79c")]
        public partial class NotepadAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _fontInfo;
            RepoItemInfo _exitInfo;

            /// <summary>
            /// Creates a new Notepad  folder.
            /// </summary>
            public NotepadAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Notepad", "/contextmenu[@processname='notepad']", parentFolder, 30000, null, true, "ec617235-78fc-46a8-966a-87d1d614a79c", "")
            {
                _fontInfo = new RepoItemInfo(this, "Font", "?/?/menuitem[@accessiblename='Font...']", 30000, null, "8b5181a6-5683-41bb-ac0d-30ba73d286de");
                _exitInfo = new RepoItemInfo(this, "Exit", "?/?/menuitem[@accessiblename='Exit']", 30000, null, "053a3d67-517e-4df5-a945-d917ded72d7f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ec617235-78fc-46a8-966a-87d1d614a79c")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ec617235-78fc-46a8-966a-87d1d614a79c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Font item.
            /// </summary>
            [RepositoryItem("8b5181a6-5683-41bb-ac0d-30ba73d286de")]
            public virtual Ranorex.MenuItem Font
            {
                get
                {
                    return _fontInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Font item info.
            /// </summary>
            [RepositoryItemInfo("8b5181a6-5683-41bb-ac0d-30ba73d286de")]
            public virtual RepoItemInfo FontInfo
            {
                get
                {
                    return _fontInfo;
                }
            }

            /// <summary>
            /// The Exit item.
            /// </summary>
            [RepositoryItem("053a3d67-517e-4df5-a945-d917ded72d7f")]
            public virtual Ranorex.MenuItem Exit
            {
                get
                {
                    return _exitInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Exit item info.
            /// </summary>
            [RepositoryItemInfo("053a3d67-517e-4df5-a945-d917ded72d7f")]
            public virtual RepoItemInfo ExitInfo
            {
                get
                {
                    return _exitInfo;
                }
            }
        }

        /// <summary>
        /// The FontAppFolder folder.
        /// </summary>
        [RepositoryFolder("73535243-5646-4236-b57f-f63f86fb8dcc")]
        public partial class FontAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text1001Info;
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new Font  folder.
            /// </summary>
            public FontAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Font", "/form[@title='Font']", parentFolder, 30000, null, true, "73535243-5646-4236-b57f-f63f86fb8dcc", "")
            {
                _text1001Info = new RepoItemInfo(this, "Text1001", "combobox[@controlid='1138']/text[@controlid='1001']", 30000, null, "e1f66c5c-bc65-464c-a362-bd8fd2c106e5");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "button[@text='OK']", 30000, null, "3cfa541e-4c39-42d4-ba35-46954af88fc9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("73535243-5646-4236-b57f-f63f86fb8dcc")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("73535243-5646-4236-b57f-f63f86fb8dcc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text1001 item.
            /// </summary>
            [RepositoryItem("e1f66c5c-bc65-464c-a362-bd8fd2c106e5")]
            public virtual Ranorex.Text Text1001
            {
                get
                {
                    return _text1001Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1001 item info.
            /// </summary>
            [RepositoryItemInfo("e1f66c5c-bc65-464c-a362-bd8fd2c106e5")]
            public virtual RepoItemInfo Text1001Info
            {
                get
                {
                    return _text1001Info;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("3cfa541e-4c39-42d4-ba35-46954af88fc9")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("3cfa541e-4c39-42d4-ba35-46954af88fc9")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

        /// <summary>
        /// The Notepad1AppFolder folder.
        /// </summary>
        [RepositoryFolder("5b5e43a8-e935-4170-a618-d0fece9aafdf")]
        public partial class Notepad1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _dontsaveInfo;

            /// <summary>
            /// Creates a new Notepad1  folder.
            /// </summary>
            public Notepad1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Notepad1", "/form[@title='Notepad']", parentFolder, 30000, null, true, "5b5e43a8-e935-4170-a618-d0fece9aafdf", "")
            {
                _dontsaveInfo = new RepoItemInfo(this, "DontSave", "?/?/element[@instance='1']/button[@text='Do&n''t Save']", 30000, null, "d0beb905-8013-4449-84b5-003a68f3383d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5b5e43a8-e935-4170-a618-d0fece9aafdf")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5b5e43a8-e935-4170-a618-d0fece9aafdf")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DontSave item.
            /// </summary>
            [RepositoryItem("d0beb905-8013-4449-84b5-003a68f3383d")]
            public virtual Ranorex.Button DontSave
            {
                get
                {
                    return _dontsaveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The DontSave item info.
            /// </summary>
            [RepositoryItemInfo("d0beb905-8013-4449-84b5-003a68f3383d")]
            public virtual RepoItemInfo DontSaveInfo
            {
                get
                {
                    return _dontsaveInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}