///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TesteTortoise
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TesteTortoiseRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.1")]
    [RepositoryFolder("3c2c961a-3564-4d41-91b3-1756b94141d2")]
    public partial class TesteTortoiseRepository : RepoGenBaseFolder
    {
        static TesteTortoiseRepository instance = new TesteTortoiseRepository();
        TesteTortoiseRepositoryFolders.UntitledNotepadAppFolder _untitlednotepad;
        TesteTortoiseRepositoryFolders.NotepadAppFolder _notepad;
        TesteTortoiseRepositoryFolders.Notepad1AppFolder _notepad1;

        /// <summary>
        /// Gets the singleton class instance representing the TesteTortoiseRepository element repository.
        /// </summary>
        [RepositoryFolder("3c2c961a-3564-4d41-91b3-1756b94141d2")]
        public static TesteTortoiseRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TesteTortoiseRepository() 
            : base("TesteTortoiseRepository", "/", null, 0, false, "3c2c961a-3564-4d41-91b3-1756b94141d2", ".\\RepositoryImages\\TesteTortoiseRepository3c2c961a.rximgres")
        {
            _untitlednotepad = new TesteTortoiseRepositoryFolders.UntitledNotepadAppFolder(this);
            _notepad = new TesteTortoiseRepositoryFolders.NotepadAppFolder(this);
            _notepad1 = new TesteTortoiseRepositoryFolders.Notepad1AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("3c2c961a-3564-4d41-91b3-1756b94141d2")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The UntitledNotepad folder.
        /// </summary>
        [RepositoryFolder("774cce00-826f-490d-af5a-751d33e9f04d")]
        public virtual TesteTortoiseRepositoryFolders.UntitledNotepadAppFolder UntitledNotepad
        {
            get { return _untitlednotepad; }
        }

        /// <summary>
        /// The Notepad folder.
        /// </summary>
        [RepositoryFolder("83874074-e155-4364-89f2-56fdfa99debc")]
        public virtual TesteTortoiseRepositoryFolders.NotepadAppFolder Notepad
        {
            get { return _notepad; }
        }

        /// <summary>
        /// The Notepad1 folder.
        /// </summary>
        [RepositoryFolder("1dd4c318-20e2-4648-86b6-eec5bf8ba123")]
        public virtual TesteTortoiseRepositoryFolders.Notepad1AppFolder Notepad1
        {
            get { return _notepad1; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.1")]
    public partial class TesteTortoiseRepositoryFolders
    {
        /// <summary>
        /// The UntitledNotepadAppFolder folder.
        /// </summary>
        [RepositoryFolder("774cce00-826f-490d-af5a-751d33e9f04d")]
        public partial class UntitledNotepadAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text15Info;
            RepoItemInfo _fileInfo;

            /// <summary>
            /// Creates a new UntitledNotepad  folder.
            /// </summary>
            public UntitledNotepadAppFolder(RepoGenBaseFolder parentFolder) :
                    base("UntitledNotepad", "/form[@title='Untitled - Notepad']", parentFolder, 30000, null, true, "774cce00-826f-490d-af5a-751d33e9f04d", "")
            {
                _text15Info = new RepoItemInfo(this, "Text15", "text[@controlid='15']", 30000, null, "8b563e93-8ed2-4b9c-bfdb-61a5ed333501");
                _fileInfo = new RepoItemInfo(this, "File", "?/?/menuitem[@accessiblename='File']", 30000, null, "340973ef-822e-4231-9b91-9bfdf188b8ed");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("774cce00-826f-490d-af5a-751d33e9f04d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("774cce00-826f-490d-af5a-751d33e9f04d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text15 item.
            /// </summary>
            [RepositoryItem("8b563e93-8ed2-4b9c-bfdb-61a5ed333501")]
            public virtual Ranorex.Text Text15
            {
                get
                {
                    return _text15Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text15 item info.
            /// </summary>
            [RepositoryItemInfo("8b563e93-8ed2-4b9c-bfdb-61a5ed333501")]
            public virtual RepoItemInfo Text15Info
            {
                get
                {
                    return _text15Info;
                }
            }

            /// <summary>
            /// The File item.
            /// </summary>
            [RepositoryItem("340973ef-822e-4231-9b91-9bfdf188b8ed")]
            public virtual Ranorex.MenuItem File
            {
                get
                {
                    return _fileInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The File item info.
            /// </summary>
            [RepositoryItemInfo("340973ef-822e-4231-9b91-9bfdf188b8ed")]
            public virtual RepoItemInfo FileInfo
            {
                get
                {
                    return _fileInfo;
                }
            }
        }

        /// <summary>
        /// The NotepadAppFolder folder.
        /// </summary>
        [RepositoryFolder("83874074-e155-4364-89f2-56fdfa99debc")]
        public partial class NotepadAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _exitInfo;

            /// <summary>
            /// Creates a new Notepad  folder.
            /// </summary>
            public NotepadAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Notepad", "/contextmenu[@processname='notepad']", parentFolder, 30000, null, true, "83874074-e155-4364-89f2-56fdfa99debc", "")
            {
                _exitInfo = new RepoItemInfo(this, "Exit", "?/?/menuitem[@accessiblename='Exit']", 30000, null, "1a4772a1-2c65-4dd1-b21c-5fbff171d52b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("83874074-e155-4364-89f2-56fdfa99debc")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("83874074-e155-4364-89f2-56fdfa99debc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Exit item.
            /// </summary>
            [RepositoryItem("1a4772a1-2c65-4dd1-b21c-5fbff171d52b")]
            public virtual Ranorex.MenuItem Exit
            {
                get
                {
                    return _exitInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Exit item info.
            /// </summary>
            [RepositoryItemInfo("1a4772a1-2c65-4dd1-b21c-5fbff171d52b")]
            public virtual RepoItemInfo ExitInfo
            {
                get
                {
                    return _exitInfo;
                }
            }
        }

        /// <summary>
        /// The Notepad1AppFolder folder.
        /// </summary>
        [RepositoryFolder("1dd4c318-20e2-4648-86b6-eec5bf8ba123")]
        public partial class Notepad1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _dontsaveInfo;

            /// <summary>
            /// Creates a new Notepad1  folder.
            /// </summary>
            public Notepad1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Notepad1", "/form[@title='Notepad']", parentFolder, 30000, null, true, "1dd4c318-20e2-4648-86b6-eec5bf8ba123", "")
            {
                _dontsaveInfo = new RepoItemInfo(this, "DontSave", "?/?/element[@instance='1']/button[@text='Do&n''t Save']", 30000, null, "f992f677-6aa5-43e2-bb22-6fd7e6795863");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1dd4c318-20e2-4648-86b6-eec5bf8ba123")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1dd4c318-20e2-4648-86b6-eec5bf8ba123")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DontSave item.
            /// </summary>
            [RepositoryItem("f992f677-6aa5-43e2-bb22-6fd7e6795863")]
            public virtual Ranorex.Button DontSave
            {
                get
                {
                    return _dontsaveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The DontSave item info.
            /// </summary>
            [RepositoryItemInfo("f992f677-6aa5-43e2-bb22-6fd7e6795863")]
            public virtual RepoItemInfo DontSaveInfo
            {
                get
                {
                    return _dontsaveInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}